name: Enviar Requisição HTTP com Python

on:
  push:
    branches:
      - main

jobs:
  send-http-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v3

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Executar script Python
      run: |
        python send_request.py
