name: Requisição HTTP com curl

on:
  push:
    branches:
      - main  # Executa a ação quando houver push no branch "main"

jobs:
  send-http-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checar o código
      uses: actions/checkout@v3

    - name: Enviar requisição HTTP
      run: |
        curl -X POST https://example.com/api -H "Content-Type: application/json" -d '{"key":"value"}'
